//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woody230.FluentValidation.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woody230.FluentValidation.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;openapi&quot;: &quot;3.0.4&quot;,
        ///  &quot;info&quot;: {
        ///    &quot;title&quot;: &quot;Woody230.FluentValidation.Web&quot;,
        ///    &quot;version&quot;: &quot;1.0&quot;
        ///  },
        ///  &quot;paths&quot;: {
        ///    &quot;/WeatherForecast&quot;: {
        ///      &quot;get&quot;: {
        ///        &quot;tags&quot;: [
        ///          &quot;WeatherForecast&quot;
        ///        ],
        ///        &quot;summary&quot;: &quot;Gets one or more weather forecasts.&quot;,
        ///        &quot;operationId&quot;: &quot;GetWeatherForecast&quot;,
        ///        &quot;responses&quot;: {
        ///          &quot;200&quot;: {
        ///            &quot;description&quot;: &quot;OK&quot;,
        ///            &quot;content&quot;: {
        ///              &quot;text/plain&quot;: {
        ///                &quot;schema&quot;: {
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swagger {
            get {
                return ResourceManager.GetString("swagger", resourceCulture);
            }
        }
    }
}
